# ============================================================
# UCI ONLINE RETAIL - CUSTOMER TABLE
# ============================================================

# EXECUTION ORDER: 3 OF 10
# RUN AFTER: invoice.sql
# RUN NEXT: product.sql

# PREREQUISITES:
# RETAIL_STG AND INVOICE MUST BE POPULATED AND VALIDATED.
# THE CUSTOMER TABLE MUST NOT ALREADY EXIST.

# FRESH BUILD ONLY:
# IF A STEP FAILS, CHECK WHAT COMPLETED BEFORE RETRYING.

# THIS SCRIPT:
# CREATES ONE CUSTOMER ROW PER DISTINCT NONBLANK SOURCE CUSTOMER ID.
# CONVERTS BLANK CUSTOMER IDS IN INVOICE TO NULL.
# ADDS THE CUSTOMER-INVOICE FOREIGN KEY.
# RETAIL_STG REMAINS UNCHANGED.

USE uci;

# COUNT SOURCE ROWS WITH EMPTY OR SPACES-ONLY CUSTOMER IDS
# NULL CUSTOMER IDS ARE COUNTED SEPARATELY.
SELECT COUNT(*) AS blank_customer_ids
FROM retail_stg
WHERE customer_id IS NOT NULL
  AND TRIM(customer_id) = '';


# COUNT SOURCE ROWS WITH NULL CUSTOMER IDS
SELECT COUNT(*) AS null_customer_ids
FROM retail_stg
WHERE customer_id IS NULL;


# COUNT SOURCE ROWS WITH NONBLANK CUSTOMER IDS
# REFERENCE DATASET: 406829 SOURCE ROWS
SELECT COUNT(*) AS rows_with_customer_id
FROM retail_stg
WHERE NULLIF(TRIM(customer_id), '') IS NOT NULL;


# IDENTIFY CUSTOMERS ASSOCIATED WITH MULTIPLE COUNTRIES
# PREVIOUSLY OBSERVED IN THE REFERENCE DATASET: EIGHT CUSTOMERS.
# RETURNED ROWS DESCRIBE A SOURCE PATTERN, NOT A VALIDATION FAILURE.
SELECT
    customer_id,
    COUNT(DISTINCT country) AS country_count
FROM retail_stg
WHERE NULLIF(TRIM(customer_id), '') IS NOT NULL
GROUP BY customer_id
HAVING COUNT(DISTINCT country) > 1
ORDER BY customer_id;


# OPTIONAL: INSPECT COUNTRY COUNTS FOR THESE CUSTOMERS
# EACH RESULT ROW REPRESENTS ONE CUSTOMER-COUNTRY COMBINATION.
# SOURCE ROW COUNT AND DISTINCT INVOICE COUNT ARE DIFFERENT MEASURES.
SELECT
    customer_id,
    country,
    COUNT(*) AS source_row_count,
    COUNT(DISTINCT invoice_no) AS invoice_count
FROM retail_stg
WHERE customer_id IN (
    SELECT customer_id
    FROM retail_stg
    WHERE NULLIF(TRIM(customer_id), '') IS NOT NULL
    GROUP BY customer_id
    HAVING COUNT(DISTINCT country) > 1
)
GROUP BY
    customer_id,
    country
ORDER BY
    customer_id,
    invoice_count DESC,
    country;


# MODELING DECISION:
# KEEP COUNTRY ON EACH INVOICE TO PRESERVE VARIATION
# ACROSS A CUSTOMER'S INVOICES.
# DO NOT ASSIGN A SINGLE COUNTRY IN THE CUSTOMER TABLE.


# COUNT DISTINCT NONBLANK SOURCE CUSTOMER IDS
# REFERENCE DATASET: 4372 DISTINCT CUSTOMER IDS
SELECT COUNT(DISTINCT customer_id) AS source_customer_count
FROM retail_stg
WHERE NULLIF(TRIM(customer_id), '') IS NOT NULL;


# CREATE CUSTOMER TABLE
# ONE ROW PER DISTINCT NONBLANK SOURCE CUSTOMER ID.
# THE PRIMARY KEY PREVENTS DUPLICATE AND NULL CUSTOMER IDS.
CREATE TABLE customer (
    customer_id VARCHAR(20) PRIMARY KEY
);


# INSERT DISTINCT NONBLANK SOURCE CUSTOMER IDS
# POPULATED CUSTOMER IDS ARE PRESERVED AS STORED IN STAGING.
INSERT INTO customer (customer_id)
SELECT DISTINCT customer_id
FROM retail_stg
WHERE NULLIF(TRIM(customer_id), '') IS NOT NULL;


# VERIFY CUSTOMER COUNT AGAINST STAGING
# VALIDATION: COUNTS MUST MATCH.
# REFERENCE DATASET: 4372 DISTINCT CUSTOMERS
# THIS COUNT INCLUDES ALL IDENTIFIED SOURCE CUSTOMERS.
# LATER PURCHASE ELIGIBILITY RULES PRODUCE THE 4334-CUSTOMER
# FEATURE TABLE. THE NOTEBOOK THEN EXCLUDES TWO CUSTOMERS,
# LEAVING 4332 FOR THE FINAL SEGMENTATION.
SELECT
    (SELECT COUNT(*) FROM customer) AS customer_count,
    (
        SELECT COUNT(DISTINCT customer_id)
        FROM retail_stg
        WHERE NULLIF(TRIM(customer_id), '') IS NOT NULL
    ) AS source_customer_count;


# CONVERT EMPTY OR SPACES-ONLY INVOICE CUSTOMER IDS TO NULL
# POPULATED CUSTOMER IDS AND RETAIL_STG REMAIN UNCHANGED.
UPDATE invoice
SET customer_id = NULL
WHERE TRIM(customer_id) = '';


# VERIFY EVERY NON-NULL INVOICE CUSTOMER EXISTS IN CUSTOMER TABLE
# VALIDATION: EXPECTED ZERO ROWS.
# INVESTIGATE ANY RESULTS BEFORE ADDING THE FOREIGN KEY.
SELECT DISTINCT
    i.customer_id
FROM invoice i
LEFT JOIN customer c
    ON i.customer_id = c.customer_id
WHERE i.customer_id IS NOT NULL
  AND c.customer_id IS NULL
ORDER BY i.customer_id;


# CREATE CUSTOMER-INVOICE FOREIGN KEY RELATIONSHIP
# NULL CUSTOMER IDS ARE ALLOWED FOR UNIDENTIFIED CUSTOMERS.
ALTER TABLE invoice
ADD CONSTRAINT fk_invoice_customer
FOREIGN KEY (customer_id)
REFERENCES customer(customer_id);


# BEFORE RUNNING product.sql:
# CONFIRM CUSTOMER COUNT MATCHES DISTINCT NONBLANK SOURCE CUSTOMER IDS.
# CONFIRM THE ORPHAN CUSTOMER CHECK RETURNED ZERO ROWS.
# CONFIRM THE CUSTOMER-INVOICE FOREIGN KEY WAS ADDED SUCCESSFULLY.
# VALIDATION QUERIES DISPLAY RESULTS; THEY DO NOT AUTOMATICALLY STOP EXECUTION.