# ============================================================
# UCI ONLINE RETAIL - FINAL VALIDATION
# ============================================================

# EXECUTION ORDER: 10 OF 10
# RUN AFTER: duplicate_sensitivity.sql

# PREREQUISITES:
# CUSTOMER_FEATURES MUST BE POPULATED.
# THE DETAILED VALIDATIONS IN customer_features.sql MUST PASS.

# PURPOSE:
# CHECK SUMMARY TOTALS IN THE PRIMARY CUSTOMER FEATURE TABLE.
# OPTIONALLY EXPORT THAT TABLE FOR A SEPARATE CSV COMPARISON.
# READ-ONLY: NO RECORDS ARE CHANGED.

# SCOPE:
# THESE CHECKS COVER THE 4334-CUSTOMER PRIMARY SQL SNAPSHOT.
# THE NOTEBOOK EXCLUDES TWO CUSTOMERS TO RETAIN 4332.
# THIS SCRIPT DOES NOT VALIDATE THE ALTERNATIVE FEATURE EXPORT
# OR THE NOTEBOOK'S CLUSTER ASSIGNMENTS.
# CHECKS DISPLAY RESULTS. THEY DO NOT AUTOMATICALLY STOP EXECUTION.

USE uci;

# 1. CHECK CUSTOMER COUNT, REFERENCE DATE, AND MONETARY TOTALS.
SELECT
    COUNT(*) AS customer_rows,
    COUNT(DISTINCT customer_id) AS distinct_customers,
    MIN(reference_date) AS minimum_reference_date,
    MAX(reference_date) AS maximum_reference_date,
    SUM(purchase_value) AS total_purchase_value,
    SUM(cancellation_value) AS total_cancellation_value
FROM customer_features;

# EXPECTED RESULTS FOR THE REFERENCE DATASET:
# CUSTOMER ROWS AND DISTINCT CUSTOMERS: 4334.
# MINIMUM AND MAXIMUM REFERENCE DATE: 2011-12-10.
# TOTAL PURCHASE VALUE: 8759761.6500.
# TOTAL CANCELLATION VALUE: 484080.0000.
# CANCELLATION VALUE COVERS QUALIFYING PURCHASING CUSTOMERS ONLY.
# THESE CHECKS COMPARE TOTALS, NOT EVERY CUSTOMER-LEVEL VALUE.
# INVESTIGATE ANY DIFFERENCES BEFORE USING OR PUBLISHING THE EXPORT.


# 2. OPTIONAL COMPARISON EXPORT OF ALL CUSTOMER FEATURES.
# USE WHEN CHECKING THE STORED TABLE AGAINST THE NOTEBOOK'S INPUT CSV.
# SET WORKBENCH'S RESULT-ROW LIMIT TO DON'T LIMIT.
# EXPECTED RESULT: 4334 CUSTOMERS AND 18 COLUMNS.
# EXPORT WITH HEADERS AS customer_features_sql_check.csv.
# PRESERVE MISSING CANCELLATION DATES AS MISSING VALUES.
# KEEP THE EXISTING customer_features.csv UNCHANGED.
# THIS SELECT DISPLAYS RESULTS. IT DOES NOT WRITE A CSV AUTOMATICALLY.
# EXPORTING ALONE DOES NOT PERFORM OR CONFIRM A FILE COMPARISON.

SELECT *
FROM customer_features
ORDER BY customer_id;