# ============================================================
# UCI ONLINE RETAIL - INVOICE TABLE
# ============================================================

# EXECUTION ORDER: 2 OF 10
# RUN AFTER: staging.sql
# RUN NEXT: customer.sql

# PREREQUISITES:
# RETAIL_STG MUST BE LOADED AND ITS VALIDATION CHECKS REVIEWED.
# THE INVOICE TABLE MUST NOT ALREADY EXIST.

# FRESH BUILD ONLY:
# IF A STEP FAILS, CHECK WHAT COMPLETED BEFORE RETRYING.

# LATER SCRIPTS:
# customer.sql CONVERTS BLANK CUSTOMER IDS TO NULL
# AND ADDS THE CUSTOMER FOREIGN KEY.
# invoice_line.sql REMOVES INVOICE RECORDS THAT HAVE NO RETAINED INVOICE LINES.

USE uci;

# CHECK FOR CONFLICTING CUSTOMER OR COUNTRY VALUES WITHIN AN INVOICE
# VALIDATION: EXPECTED ZERO ROWS.
# INVESTIGATE ANY RESULTS BEFORE CREATING THE INVOICE TABLE.
SELECT
    invoice_no,
    COUNT(DISTINCT customer_id) AS customer_count,
    COUNT(DISTINCT country) AS country_count
FROM retail_stg
GROUP BY invoice_no
HAVING
       COUNT(DISTINCT customer_id) > 1
    OR COUNT(DISTINCT country) > 1
ORDER BY invoice_no;

# CHECK FOR MISSING HEADER VALUES
# CUSTOMER IDS MAY BE MISSING FOR AN ENTIRE INVOICE.
# A MIXTURE OF MISSING AND POPULATED CUSTOMER IDS REQUIRES REVIEW.
# MISSING COUNTRIES OR INVOICE DATES ALSO REQUIRE REVIEW.
# VALIDATION: EXPECTED ZERO ROWS.
SELECT
    invoice_no,
    COUNT(*) AS source_line_count,
    SUM(
        CASE WHEN NULLIF(TRIM(customer_id), '') IS NULL
             THEN 1 ELSE 0 END
    ) AS missing_customer_rows,
    SUM(
        CASE WHEN NULLIF(TRIM(country), '') IS NULL
             THEN 1 ELSE 0 END
    ) AS missing_country_rows,
    SUM(
        CASE WHEN invoice_date IS NULL
             THEN 1 ELSE 0 END
    ) AS missing_date_rows
FROM retail_stg
GROUP BY invoice_no
HAVING
       (missing_customer_rows > 0
        AND missing_customer_rows < source_line_count)
    OR missing_country_rows > 0
    OR missing_date_rows > 0
ORDER BY invoice_no;

# MEASURE TIMESTAMP DIFFERENCES WITHIN EACH INVOICE
# RETURNS ONLY INVOICES WITH MORE THAN ONE DISTINCT TIMESTAMP.
SELECT
    invoice_no,
    COUNT(DISTINCT invoice_date) AS timestamp_count,
    MIN(invoice_date) AS earliest_invoice_date,
    MAX(invoice_date) AS latest_invoice_date,
    TIMESTAMPDIFF(
        SECOND,
        MIN(invoice_date),
        MAX(invoice_date)
    ) AS timestamp_span_seconds
FROM retail_stg
GROUP BY invoice_no
HAVING COUNT(DISTINCT invoice_date) > 1
ORDER BY
    timestamp_span_seconds DESC,
    invoice_no;


# PREVIOUSLY OBSERVED IN THE REFERENCE DATASET:
# INVOICES WITH MULTIPLE TIMESTAMPS HAVE A 60-SECOND SPAN.

# MODELING DECISION:
# USE THE EARLIEST SOURCE TIMESTAMP AS THE INVOICE DATETIME.

# REVIEW ANY DIFFERENT TIMESTAMP SPANS BEFORE CONTINUING.


# CREATE INVOICE TABLE
# ONE ROW PER INVOICE NUMBER.
# CUSTOMER_ID REMAINS NULLABLE TO ALLOW UNIDENTIFIED CUSTOMERS.
# COUNTRY IS STORED AT THE INVOICE LEVEL.
CREATE TABLE invoice (
    invoice_no VARCHAR(20) PRIMARY KEY,
    invoice_date DATETIME,
    customer_id VARCHAR(20),
    country VARCHAR(50)
);


# POPULATE INVOICE TABLE
# CREATE ONE HEADER PER SOURCE INVOICE NUMBER.
# MIN(INVOICE_DATE) IMPLEMENTS THE EARLIEST-TIMESTAMP RULE.
# MIN(CUSTOMER_ID) AND MIN(COUNTRY) COLLAPSE REPEATED VALUES
# AFTER CUSTOMER AND COUNTRY CONSISTENCY HAS BEEN VERIFIED.
# DO NOT USE MIN() TO RESOLVE CONFLICTING CUSTOMERS OR COUNTRIES.
INSERT INTO invoice (
    invoice_no,
    invoice_date,
    customer_id,
    country
)
SELECT
    invoice_no,
    MIN(invoice_date),
    MIN(customer_id),
    MIN(country)
FROM retail_stg
GROUP BY invoice_no;


# VALIDATION: COUNTS MUST MATCH AT THIS STAGE.
# LATER INVOICE-LINE CLEANUP MAY REDUCE THE INVOICE COUNT.
SELECT
    (SELECT COUNT(*) FROM invoice) AS invoice_count,
    (SELECT COUNT(DISTINCT invoice_no) FROM retail_stg)
        AS source_invoice_count;

# BEFORE RUNNING customer.sql:
# RESOLVE CUSTOMER OR COUNTRY CONSISTENCY ISSUES.
# REVIEW MISSING VALUES AND TIMESTAMP DIFFERENCES.
# CONFIRM INVOICE COUNT MATCHES DISTINCT SOURCE INVOICE NUMBERS.
# THESE CHECKS DISPLAY RESULTS; THEY DO NOT AUTOMATICALLY STOP EXECUTION.