# ============================================================
# UCI ONLINE RETAIL - PRODUCT TABLE
# ============================================================

# EXECUTION ORDER: 4 OF 10
# RUN AFTER: customer.sql
# RUN NEXT: invoice_line.sql

# PREREQUISITES:
# RETAIL_STG MUST BE LOADED AND VALIDATED.
# THE PRODUCT TABLE MUST NOT ALREADY EXIST.
# MYSQL 8.0 OR LATER IS REQUIRED FOR WINDOW FUNCTIONS.

# FRESH BUILD ONLY:
# IF A STEP FAILS, CHECK WHAT COMPLETED BEFORE RETRYING.

# SESSION REQUIREMENT:
# RUN THE TEMPORARY-TABLE WORKFLOW IN ONE CONNECTION.
# RECONNECTING REMOVES THE TEMPORARY TABLES.

# THIS SCRIPT:
# SELECTS ONE DESCRIPTION PER RETAINED STOCK CODE.
# RESOLVES SELECTED DESCRIPTION TIES MANUALLY.
# RETAIL_STG REMAINS UNCHANGED.
# STOCK CODES EXCLUDED HERE ARE ALSO EXCLUDED FROM INVOICE_LINE.

# PRODUCT MEMBERSHIP INDICATES A RETAINED STOCK CODE WITH A SELECTED DESCRIPTION.
# IT DOES NOT ESTABLISH THAT THE CODE REPRESENTS MERCHANDISE.
# SPECIAL CHARGES AND OTHER RECORD TYPES ARE REVIEWED IN transaction_cleaning.sql.


USE uci;

# COUNT SOURCE ROWS WITH MISSING PRODUCT DESCRIPTIONS
# MISSING MEANS NULL, EMPTY, OR SPACES-ONLY.
# PREVIOUSLY OBSERVED: 1454 SOURCE ROWS WITH EMPTY DESCRIPTIONS.
SELECT COUNT(*) AS missing_description_rows
FROM retail_stg
WHERE NULLIF(TRIM(product_description), '') IS NULL;


# COUNT DISTINCT STOCK CODES APPEARING ON MISSING-DESCRIPTION ROWS
# PREVIOUSLY OBSERVED: 960 STOCK CODES ON EMPTY-DESCRIPTION ROWS.
# THESE STOCK CODES MAY HAVE POPULATED DESCRIPTIONS ON OTHER ROWS.
SELECT COUNT(DISTINCT stock_code) AS stock_codes_with_missing_descriptions
FROM retail_stg
WHERE NULLIF(TRIM(product_description), '') IS NULL;


# COUNT ALL DISTINCT SOURCE STOCK CODES
# PREVIOUSLY OBSERVED: 3958 DISTINCT STOCK CODES.
SELECT COUNT(DISTINCT stock_code) AS total_stock_codes
FROM retail_stg;


# IDENTIFY STOCK CODES WITH MULTIPLE DISTINCT NONBLANK DESCRIPTIONS
# TRIM LEADING AND TRAILING SPACES FOR COMPARISON.
# RETURNED ROWS REQUIRE DESCRIPTION SELECTION, NOT AUTOMATIC EXCLUSION.
SELECT
    stock_code,
    COUNT(DISTINCT TRIM(product_description)) AS description_count
FROM retail_stg
WHERE NULLIF(TRIM(product_description), '') IS NOT NULL
GROUP BY stock_code
HAVING COUNT(DISTINCT TRIM(product_description)) > 1
ORDER BY
    description_count DESC,
    stock_code;


# OPTIONAL: INVESTIGATE DESCRIPTIONS FOR SELECTED STOCK CODES
# COUNT SOURCE ROWS FOR EACH TRIMMED NONBLANK DESCRIPTION.
# FIRST_SEEN AND LAST_SEEN REFER TO SOURCE INVOICE TIMESTAMPS.
SELECT
    stock_code,
    TRIM(product_description) AS product_description,
    COUNT(*) AS source_row_count,
    MIN(invoice_date) AS first_seen,
    MAX(invoice_date) AS last_seen
FROM retail_stg
WHERE stock_code IN (
    '20713',
    '23084',
    '21830',
    '85175',
    '21181'
)
  AND NULLIF(TRIM(product_description), '') IS NOT NULL
GROUP BY
    stock_code,
    TRIM(product_description)
ORDER BY
    stock_code,
    source_row_count DESC,
    product_description;


# IDENTIFY STOCK CODES WITH NO NONBLANK DESCRIPTION ANYWHERE IN STAGING
# ALL SOURCE DESCRIPTIONS FOR THESE CODES ARE NULL, EMPTY, OR SPACES-ONLY.
# THESE ARE CANDIDATES FOR EXCLUSION; REVIEW THE CHECK BELOW.
SELECT
    stock_code
FROM retail_stg
GROUP BY stock_code
HAVING COUNT(NULLIF(TRIM(product_description), '')) = 0
ORDER BY stock_code;


# CHECK EXCLUSION CANDIDATES FOR NONZERO OR MISSING PRICES
# AND FOR POPULATED CUSTOMER IDS.
# VALIDATION: EXPECTED ZERO ROWS.
# INVESTIGATE ANY RESULTS BEFORE ACCEPTING THE EXCLUSION.
SELECT
    stock_code,
    SUM(
        CASE WHEN unit_price <> 0
             THEN 1 ELSE 0 END
    ) AS nonzero_price_rows,
    SUM(
        CASE WHEN unit_price IS NULL
             THEN 1 ELSE 0 END
    ) AS missing_price_rows,
    SUM(
        CASE WHEN NULLIF(TRIM(customer_id), '') IS NOT NULL
             THEN 1 ELSE 0 END
    ) AS populated_customer_rows
FROM retail_stg
WHERE stock_code IN (
    SELECT stock_code
    FROM retail_stg
    GROUP BY stock_code
    HAVING COUNT(NULLIF(TRIM(product_description), '')) = 0
)
GROUP BY stock_code
HAVING
       nonzero_price_rows > 0
    OR missing_price_rows > 0
    OR populated_customer_rows > 0
ORDER BY stock_code;


# TEMPORARY-TABLE WORKFLOW
# START IN A CONNECTION WHERE THESE TEMPORARY TABLES DO NOT EXIST.
# RUN ALL REMAINING STEPS IN THE SAME CONNECTION.


# STEP 1: COUNT SOURCE ROWS FOR EACH TRIMMED NONBLANK DESCRIPTION
# EXCLUDE NULL, EMPTY, AND SPACES-ONLY DESCRIPTIONS.
# FREQUENCY COUNTS ALL SOURCE ROWS, INCLUDING RETURNS AND ADJUSTMENTS.

# DESCRIPTION GROUPING USES THE SOURCE COLUMN'S COLLATION.
# WITH utf8mb4_0900_ai_ci, CASE AND ACCENT DIFFERENCES
# DO NOT CREATE SEPARATE DESCRIPTION GROUPS.
# TRIM REMOVES LEADING AND TRAILING SPACES BEFORE GROUPING.

# THIS DIFFERS FROM THE BINARY COMPARISONS USED TO IDENTIFY
# EXACT SOURCE DUPLICATES IN transaction_cleaning.sql.
# RETAIL_STG REMAINS UNCHANGED.
CREATE TEMPORARY TABLE product_description_counts AS
SELECT
    stock_code,
    TRIM(product_description) AS product_description,
    COUNT(*) AS description_count
FROM retail_stg
WHERE NULLIF(TRIM(product_description), '') IS NOT NULL
GROUP BY
    stock_code,
    TRIM(product_description);


# OPTIONAL: INSPECT DESCRIPTION FREQUENCIES
SELECT
    stock_code,
    product_description,
    description_count
FROM product_description_counts
ORDER BY
    stock_code,
    description_count DESC,
    product_description;


# STEP 2: RANK DESCRIPTIONS BY FREQUENCY WITHIN EACH STOCK CODE
# RANK 1 IDENTIFIES THE MOST FREQUENT DESCRIPTION(S).
# DENSE_RANK PRESERVES TIES FOR LATER REVIEW.
CREATE TEMPORARY TABLE product_description_ranked AS
SELECT
    stock_code,
    product_description,
    description_count,
    DENSE_RANK() OVER (
        PARTITION BY stock_code
        ORDER BY description_count DESC
    ) AS description_rank
FROM product_description_counts;


# OPTIONAL: INSPECT THE MOST FREQUENT DESCRIPTION(S) FOR EACH STOCK CODE
SELECT
    stock_code,
    product_description,
    description_count,
    description_rank
FROM product_description_ranked
WHERE description_rank = 1
ORDER BY
    stock_code,
    product_description;


# STEP 3: RETAIN TOP-RANKED DESCRIPTIONS AND COUNT THEM PER STOCK CODE
# TIED_DESCRIPTIONS = 1 MEANS THERE IS ONE MOST FREQUENT DESCRIPTION.
# TIED_DESCRIPTIONS > 1 MEANS MULTIPLE DESCRIPTIONS SHARE FIRST PLACE.
CREATE TEMPORARY TABLE top_product_descriptions AS
SELECT
    stock_code,
    product_description,
    description_count,
    COUNT(*) OVER (
        PARTITION BY stock_code
    ) AS tied_descriptions
FROM product_description_ranked
WHERE description_rank = 1;


# STEP 4: REVIEW STOCK CODES WITH TIED MOST FREQUENT DESCRIPTIONS
# EACH RESULT ROW IS ONE TIED DESCRIPTION, NOT ONE DISTINCT STOCK CODE.
# EACH AFFECTED STOCK CODE NEEDS A MANUAL RESOLUTION
# OR AN EXPLICITLY DOCUMENTED EXCLUSION BEFORE PRODUCT INSERTION.
SELECT
    stock_code,
    product_description,
    description_count,
    tied_descriptions
FROM top_product_descriptions
WHERE tied_descriptions > 1
ORDER BY
    stock_code,
    product_description;
    
    
# REVIEW STOCK CODE 23595 BEFORE EXCLUDING IT FROM PRODUCT
# PREVIOUSLY OBSERVED IN THE REFERENCE DATASET:
# TWO SOURCE ROWS WITH DESCRIPTIONS "adjustment" AND "re-adjustment",
# QUANTITIES +5 AND -5, ZERO UNIT PRICES, AND MISSING CUSTOMER IDS.
SELECT
    invoice_no,
    stock_code,
    product_description,
    quantity,
    invoice_date,
    unit_price,
    customer_id,
    country
FROM retail_stg
WHERE stock_code = '23595'
ORDER BY
    invoice_date,
    invoice_no,
    product_description;


# MODELING DECISION:
# EXCLUDE STOCK CODE 23595 FROM PRODUCT BECAUSE ITS SOURCE RECORDS
# DESCRIBE INVENTORY ADJUSTMENTS WITHOUT A USABLE PRODUCT DESCRIPTION.
# ITS SOURCE ROWS REMAIN IN RETAIL_STG.
# THEY WILL ALSO BE EXCLUDED FROM INVOICE_LINE.

# CONFIRM THE OBSERVED DETAILS ABOVE BEFORE ACCEPTING THIS EXCLUSION.
# THIS QUERY ONLY DISPLAYS THE SOURCE RECORDS; IT DOES NOT EXCLUDE THEM.


# CREATE TEMPORARY TABLE FOR MANUAL DESCRIPTION TIE RESOLUTIONS
# ONE SELECTED DESCRIPTION PER MANUALLY RESOLVED STOCK CODE.
# THESE ENTRIES WILL BE INSERTED INTO PRODUCT IN A LATER STEP.
CREATE TEMPORARY TABLE product_description_overrides (
    stock_code VARCHAR(20) PRIMARY KEY,
    product_description VARCHAR(255) NOT NULL
);


# RECORD THE NINE MANUAL DESCRIPTION SELECTIONS
# THESE ARE FIXED MODELING CHOICES FOR THE REFERENCE DATASET.
# REVIEW THEM IF THE SOURCE DATA OR DESCRIPTION RANKINGS CHANGE.
# STOCK CODE 23595 IS INTENTIONALLY EXCLUDED AS DOCUMENTED ABOVE.
INSERT INTO product_description_overrides (
    stock_code,
    product_description
)
VALUES
    ('35610B', 'BLACK CHRISTMAS FLOCK DROPLET'),
    ('35817P', 'PINK ACRYLIC JEWEL SNOWFLAKE'),
    ('35833G', '4 GOLD FLOCK CHRISTMAS BALLS'),
    ('79323W', 'WHITE CHERRY LIGHTS'),
    ('84614A', 'PINK BAROQUE FLOCK CANDLE HOLDER'),
    ('84743C', 'ORANGE FELT VASE + FLOWERS'),
    ('84809B', 'PINK CHRYSANTHEMUMS ART FLOWER'),
    ('90014C', 'SILVER AND BLACK ORBIT NECKLACE'),
    ('DCGS0069', 'OOH LA LA DOGS COLLAR');
    
# VERIFY MANUAL SELECTIONS MATCH TIED TOP-RANKED DESCRIPTIONS
# VALIDATION: EXPECTED ZERO ROWS.
# FLAGS UNKNOWN STOCK CODES, NON-TIED PRODUCTS, OR DESCRIPTIONS
# THAT DO NOT MATCH A TIED TOP-RANKED SOURCE DESCRIPTION.
SELECT
    o.stock_code,
    o.product_description
FROM product_description_overrides o
LEFT JOIN top_product_descriptions t
    ON o.stock_code = t.stock_code
   AND o.product_description = t.product_description
   AND t.tied_descriptions > 1
WHERE t.stock_code IS NULL
ORDER BY o.stock_code;


# VERIFY ALL DESCRIPTION TIES HAVE BEEN ADDRESSED
# VALIDATION: EXPECTED ZERO ROWS.
# STOCK CODE 23595 IS THE DOCUMENTED INTENTIONAL EXCLUSION.
SELECT DISTINCT
    t.stock_code
FROM top_product_descriptions t
LEFT JOIN product_description_overrides o
    ON t.stock_code = o.stock_code
WHERE t.tied_descriptions > 1
  AND o.stock_code IS NULL
  AND t.stock_code <> '23595'
ORDER BY t.stock_code;


# STOP AND INVESTIGATE ANY RESULTS FROM THE TWO CHECKS ABOVE.
# THESE QUERIES DISPLAY ISSUES; THEY DO NOT AUTOMATICALLY STOP EXECUTION.


# CREATE PRODUCT TABLE
# ONE ROW PER RETAINED STOCK CODE.
# THE PRIMARY KEY PREVENTS DUPLICATE AND NULL STOCK CODES.
# PRODUCT DESCRIPTIONS MUST NOT BE NULL.
CREATE TABLE product (
    stock_code VARCHAR(20) PRIMARY KEY,
    product_description VARCHAR(255) NOT NULL
);


# INSERT PRODUCTS WITH ONE MOST FREQUENT NONBLANK DESCRIPTION
# APPLY THE DOCUMENTED EXCLUSION OF STOCK CODE 23595 EXPLICITLY.
INSERT INTO product (
    stock_code,
    product_description
)
SELECT
    stock_code,
    product_description
FROM top_product_descriptions
WHERE tied_descriptions = 1
  AND stock_code <> '23595';


# INSERT MANUALLY RESOLVED PRODUCTS
INSERT INTO product (
    stock_code,
    product_description
)
SELECT
    stock_code,
    product_description
FROM product_description_overrides
WHERE stock_code <> '23595';


# VERIFY PRODUCT COUNT AGAINST THE SELECTED INPUTS
# VALIDATION: ACTUAL AND EXPECTED COUNTS MUST MATCH.
# THE PRE-INSERT CHECKS MUST PASS FOR THIS COMPARISON TO BE MEANINGFUL.
SELECT
    (SELECT COUNT(*) FROM product) AS product_count,
    (
        SELECT COUNT(*)
        FROM top_product_descriptions
        WHERE tied_descriptions = 1
          AND stock_code <> '23595'
    ) + (
        SELECT COUNT(*)
        FROM product_description_overrides
        WHERE stock_code <> '23595'
    ) AS expected_product_count;


# VERIFY EVERY PRODUCT HAS A NONBLANK DESCRIPTION
# VALIDATION: EXPECTED ZERO ROWS.
SELECT
    stock_code,
    product_description
FROM product
WHERE NULLIF(TRIM(product_description), '') IS NULL
ORDER BY stock_code;


# VERIFY EVERY MANUAL SELECTION WAS INSERTED WITH ITS CHOSEN DESCRIPTION
# VALIDATION: EXPECTED ZERO ROWS.
# THE LEFT JOIN ALSO DETECTS MISSING PRODUCTS.
SELECT
    o.stock_code,
    o.product_description AS selected_description,
    p.product_description AS inserted_description
FROM product_description_overrides o
LEFT JOIN product p
    ON o.stock_code = p.stock_code
WHERE p.stock_code IS NULL
   OR NOT (p.product_description <=> o.product_description)
ORDER BY o.stock_code;


# VERIFY THE INTENTIONALLY EXCLUDED STOCK CODE IS ABSENT
# VALIDATION: EXPECTED ZERO ROWS.
SELECT
    stock_code,
    product_description
FROM product
WHERE stock_code = '23595';


# CHECK FOR UNEXPECTEDLY EXCLUDED STOCK CODES
# VALIDATION: EXPECTED ZERO ROWS.
# ANY CODE WITH A NONBLANK SOURCE DESCRIPTION SHOULD BE RETAINED,
# EXCEPT THE DOCUMENTED EXCLUSION OF 23595.
SELECT DISTINCT
    r.stock_code
FROM retail_stg r
LEFT JOIN product p
    ON r.stock_code = p.stock_code
WHERE p.stock_code IS NULL
  AND NULLIF(TRIM(r.product_description), '') IS NOT NULL
  AND r.stock_code <> '23595'
ORDER BY r.stock_code;


# BEFORE RUNNING invoice_line.sql:
# CONFIRM MANUAL SELECTIONS MATCH TIED TOP-RANKED DESCRIPTIONS.
# CONFIRM NO UNDOCUMENTED DESCRIPTION TIES REMAIN UNRESOLVED.
# CONFIRM ACTUAL AND EXPECTED PRODUCT COUNTS MATCH.
# CONFIRM ALL PRODUCT DESCRIPTIONS ARE NONBLANK.
# CONFIRM ALL MANUAL SELECTIONS WERE INSERTED CORRECTLY.
# CONFIRM 23595 IS ABSENT AND NO UNEXPECTED EXCLUSIONS REMAIN.
# CONFIRM THE EARLIER REVIEW OF CODES WITH NO DESCRIPTION PASSED.
# VALIDATION QUERIES DISPLAY RESULTS; THEY DO NOT AUTOMATICALLY STOP EXECUTION.