# ============================================================
# UCI ONLINE RETAIL - STAGING TABLE
# ============================================================

# EXECUTION ORDER: 1 OF 10
# RUN NEXT: invoice.sql

# PREREQUISITES:
# THE UCI SCHEMA MUST NOT ALREADY EXIST.
# THE PREPARED CSV MUST BE AVAILABLE AT THE LOAD DATA INFILE PATH
# AND ACCESSIBLE TO THE MYSQL SERVER.

# REQUIRES MYSQL 8.0 OR A COMPATIBLE MYSQL VERSION.
# THE ACCOUNT MUST HAVE PERMISSION TO CREATE THE SCHEMA AND TABLE,
# AND THE FILE PRIVILEGE REQUIRED BY LOAD DATA INFILE.
# CHECK secure_file_priv FOR THE SERVER'S PERMITTED IMPORT DIRECTORY.
# FRESH BUILD ONLY:

# RUN THIS SCRIPT ONCE TO CREATE AND POPULATE THE STAGING TABLE.
# RERUNNING THE LOAD DATA STATEMENT APPENDS THE SOURCE ROWS AGAIN.
# IF A STEP FAILS, CHECK WHAT COMPLETED BEFORE RETRYING.
# DO NOT SKIP CREATION ERRORS AND CONTINUE LOADING INTO EXISTING TABLES.

# CREATE SCHEMA
# USE THE CHARACTER SET AND COLLATION FROM THE VALIDATED BUILD.
# UTF8MB4 SUPPORTS UNICODE TEXT.
# THIS COLLATION USES CASE-INSENSITIVE AND ACCENT-INSENSITIVE COMPARISONS.

CREATE SCHEMA uci
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE uci;


# CREATE SOURCE STAGING TABLE
# SOURCE ROWS ARE RETAINED; VALUES ARE LOADED INTO TYPED COLUMNS.
# INVOICE DATES ARE PARSED DURING IMPORT.
# BUSINESS CLEANING AND EXCLUSIONS OCCUR IN LATER SCRIPTS.
CREATE TABLE retail_stg (
    invoice_no VARCHAR(20),
    stock_code VARCHAR(20),
    product_description VARCHAR(255),
    quantity INT,
    invoice_date DATETIME,
    unit_price DECIMAL(10,4),
    customer_id VARCHAR(20),
    country VARCHAR(50)
);


# SOURCE AND CSV PREPARATION
# SOURCE: UCI MACHINE LEARNING REPOSITORY - ONLINE RETAIL
# DOWNLOAD: https://archive.ics.uci.edu/static/public/352/online+retail.zip

# PREPARATION USED FOR THIS PROJECT:
# 1. EXTRACT THE XLSX WORKBOOK FROM THE ZIP FILE.
# 2. OPEN THE WORKBOOK IN EXCEL AND SAVE THE DATA WORKSHEET
#    USING THE "CSV UTF-8 (Comma delimited) (*.csv)" FILE TYPE.
# 3. NAME THE CSV Online_Retail.csv.
# 4. PLACE IT IN THE MYSQL SERVER'S PERMITTED IMPORT DIRECTORY.

# EXCEL DATE FORMATTING CAN VARY BY REGIONAL SETTINGS.
# CHECK THE ACTUAL CSV DATE VALUES BEFORE IMPORTING.
# ADJUST THE CSV FORMAT OR STR_TO_DATE FORMAT IF THEY DIFFER.

# PYTHON OR ANOTHER CONVERSION METHOD MAY ALSO BE USED.
# THE RESULTING CSV MUST MATCH THE IMPORT SETTINGS BELOW.

# VERIFIED FILE FORMAT:
# ENCODING: UTF-8 WITH BOM.
# LINE ENDINGS: WINDOWS CRLF (\r\n).

# EXPECTED CSV STRUCTURE:
# COMMA-SEPARATED FIELDS WITH DOUBLE-QUOTE TEXT ENCLOSURE.
# ONE HEADER ROW, WHICH THE IMPORT SKIPS.
# PRESERVE THE ORIGINAL EIGHT-COLUMN ORDER:
# INVOICE NUMBER, STOCK CODE, DESCRIPTION, QUANTITY,
# INVOICE DATE, UNIT PRICE, CUSTOMER ID, COUNTRY.

# THE DATE PARSER EXPECTS MONTH/DAY/YEAR HOUR:MINUTE.
# EXAMPLE: 12/1/2010 8:26

# LOAD DATA INFILE READS FROM THE MYSQL SERVER'S FILESYSTEM.
# UPDATE THE PATH BELOW TO THE PERMITTED LOCATION OF YOUR CSV.

# LOAD SOURCE DATA
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Online_Retail.csv'
INTO TABLE retail_stg
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(
    invoice_no,
    stock_code,
    product_description,
    quantity,
    @invoice_date,
    unit_price,
    customer_id,
    country
)
SET invoice_date = STR_TO_DATE(@invoice_date, '%c/%e/%Y %k:%i');

# INSPECT WARNINGS FROM THE IMPORT
SHOW WARNINGS;

# VALIDATION: EACH COUNT SHOULD BE ZERO BEFORE CONTINUING
SELECT
    COUNT(CASE WHEN NULLIF(TRIM(invoice_no), '') IS NULL
               THEN 1 END) AS missing_invoice_numbers,
    COUNT(CASE WHEN NULLIF(TRIM(stock_code), '') IS NULL
               THEN 1 END) AS missing_stock_codes,
    COUNT(CASE WHEN invoice_date IS NULL
               THEN 1 END) AS missing_or_unparsed_invoice_dates
FROM retail_stg;

# INSPECT DATA TYPES
DESC retail_stg;


# VERIFY IMPORTED SOURCE ROW COUNT
# REFERENCE DATASET: 541909 SOURCE ROWS
# THIS QUERY RETURNS ONE RESULT ROW CONTAINING THE COUNT.
SELECT COUNT(*) AS staging_row_count
FROM retail_stg;

# BEFORE RUNNING invoice.sql:
# REVIEW IMPORT WARNINGS AND RESOLVE ANY IMPORT PROBLEMS.
# CONFIRM ALL THREE REQUIRED-FIELD COUNTS ARE ZERO.
# CONFIRM THE STAGING ROW COUNT MATCHES THE REFERENCE DATASET.
# THESE CHECKS DISPLAY RESULTS; THEY DO NOT AUTOMATICALLY STOP EXECUTION.